language: python

python:
  - "3.6"
#  - "nightly"

before_install:
  - export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")

install:
  - pip install .
  - pip install -r requirements.txt

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
# Configure headless display for matplotlib
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

script:
  - pytest --cov=pynucastro --nbval pynucastro examples -v
#  - travis-sphinx build --source=docs

#after_success:
#  - travis-sphinx deploy

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
