dist: bionic

language: python
python:
  - '3.6'
  - '3.7'
  - '3.8'

before_install:
  - export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")

addons:
  apt_packages:
  - pandoc

install:
  - pip install .
  - pip install -r requirements.txt

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)

script:
  - pytest -v --cov=. --nbval --ignore=docs --ignore=pynucastro/library/tabular/*.ipynb

