language: python

python:
  - "3.6"
  - "3.5"
  - "3.4"

before_install:
  - export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")

addons:
  apt_packages:
    - pandoc

install:
  - pip install .
  - pip install -r requirements.txt

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)

script:
  - pytest -v --cov=. --nbval --ignore=docs
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then
      travis-sphinx build;
    fi

after_success:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then
      travis-sphinx deploy;
    fi

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
