language: python

python:
  - "3.6"
  - "nightly"

before_install:
  - export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")

install:
  - pip install .
  - pip install -r requirements.txt

script:
  - pytest --cov=pynucastro --nbval pynucastro examples -v
  - travis-sphinx build --source=docs

after_success:
  - travis-sphinx deploy

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
