name: pytest

on: [pull_request]

jobs:
  test_3_8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Cache pip
        uses: actions/cache@v2
        with:
          # this path is specific to Ubuntu
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install pynucastro
        run: python setup.py install --user

      - name: Run tests with pytest
        run: pytest -v --cov=. --nbval --ignore=docs --ignore-glob="pynucastro/library/tabular/*.ipynb"
