name: Run Python Tests

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install pynucastro
        run: python setup.py install --user

      - name: Run tests with pytest
        run: pytest -v --cov=. --nbval --ignore=docs --ignore=pynucastro/library/tabular/*.ipynb
